# Generated by Django 5.0.14 on 2026-04-22 00:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryArticle",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("content", models.TextField(help_text="Standard Markdown content.")),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                ("is_live", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)ss", to="core.tenant"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PortfolioAsset",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "anchor_type",
                    models.CharField(
                        choices=[
                            ("AUDIT", "Revenue Leakage Audit"),
                            ("INTELLIGENCE", "Data Intelligence Dashboard"),
                            ("STANDARD", "Standard Case Study"),
                        ],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                ("raw_star_data", models.JSONField(default=dict, help_text="Raw JSON input for AI processing.")),
                (
                    "published_content",
                    models.TextField(blank=True, help_text="AI-generated, SEO-ready Markdown/HTML."),
                ),
                ("is_live", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)ss", to="core.tenant"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DataAnchor",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("identifier", models.CharField(help_text="e.g., 'revenue_leakage_2026'", max_length=100)),
                ("title", models.CharField(max_length=255)),
                (
                    "payload",
                    models.JSONField(default=dict, help_text="The exact JSON structure expected by Recharts/D3.js."),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)ss", to="core.tenant"
                    ),
                ),
            ],
            options={
                "unique_together": {("tenant", "identifier")},
            },
        ),
    ]
