# Generated by Django 5.0.14 on 2026-04-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="libraryarticle",
            old_name="is_live",
            new_name="is_published",
        ),
        migrations.RenameField(
            model_name="portfolioasset",
            old_name="is_live",
            new_name="is_published",
        ),
        migrations.AddField(
            model_name="libraryarticle",
            name="keywords",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="libraryarticle",
            name="meta_description",
            field=models.TextField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="libraryarticle",
            name="meta_title",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="portfolioasset",
            name="keywords",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="portfolioasset",
            name="meta_description",
            field=models.TextField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="portfolioasset",
            name="meta_title",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
