# Generated by Django 5.0.14 on 2026-04-29 12:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("portfolio", "0002_rename_is_live_libraryarticle_is_published_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetMedia",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="portfolio_media/")),
                ("alt_text", models.CharField(blank=True, help_text="SEO alt text for the image.", max_length=255)),
                (
                    "portfolio_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_gallery",
                        to="portfolio.portfolioasset",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)ss", to="core.tenant"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
